/* Generated by cbindgen: do not edit */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif

void rust_init_motor_control(float rs,
                             float ls,
                             float lambda_m,
                             uint32_t p,
                             float j,
                             float b,
                             float dt,
                             float kp_id,
                             float ki_id,
                             float kp_iq,
                             float ki_iq,
                             float out_min_id,
                             float out_max_id,
                             float out_min_iq,
                             float out_max_iq);

void rust_motor_step(float target_id,
                     float target_iq,
                     float load_torque,
                     float v_bus,
                     float i_a,
                     float i_b,
                     float i_c,
                     float *output_vd,
                     float *output_vq,
                     float *output_id,
                     float *output_iq,
                     float *output_electrical_angle,
                     float *output_mechanical_speed,
                     float *output_ia_fb,
                     float *output_ib_fb,
                     float *output_ic_fb);

int32_t rust_add(int32_t a, int32_t b);

void rust_get_abc_from_dq(float id,
                          float iq,
                          float electrical_angle,
                          float *output_ia,
                          float *output_ib,
                          float *output_ic);

#ifdef __cplusplus
}
#endif
